In [3]:
import numpy as np

In [5]:
minha_lista = [1,2,3]

In [6]:
minha_lista

[1, 2, 3]

In [7]:
np.array(minha_lista)

array([1, 2, 3])

In [8]:
minha_matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
arr = np.zeros(3)

In [14]:
arr

array([0., 0., 0.])

In [15]:
arr = np.zeros((5,5))

In [16]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.random.rand(5)

array([0.56118286, 0.67678162, 0.19688385, 0.98669382, 0.31870025])

In [25]:
np.random.rand(5,4,3)

array([[[0.42854582, 0.23774665, 0.6123083 ],
        [0.61804759, 0.45259495, 0.92352655],
        [0.4637609 , 0.77609618, 0.46339903],
        [0.52230658, 0.14835966, 0.84363022]],

       [[0.6842731 , 0.57556441, 0.85886513],
        [0.09257625, 0.27149022, 0.88895318],
        [0.63800884, 0.4272893 , 0.28557978],
        [0.60326857, 0.5247249 , 0.72753667]],

       [[0.15980466, 0.39448008, 0.15436688],
        [0.16485324, 0.2858492 , 0.93688688],
        [0.97244741, 0.80023037, 0.02967447],
        [0.24839905, 0.60554363, 0.678632  ]],

       [[0.67222695, 0.09675145, 0.30075998],
        [0.22069583, 0.46129111, 0.47975126],
        [0.22319549, 0.50840947, 0.62713439],
        [0.85624482, 0.51308111, 0.83467341]],

       [[0.62470258, 0.03007054, 0.97682845],
        [0.41627646, 0.08319953, 0.38910593],
        [0.83914224, 0.58896292, 0.61770933],
        [0.0279888 , 0.34639899, 0.06220577]]])

In [27]:
np.random.randn(4)

array([ 0.84230482, -1.61953216, -0.45159641, -0.11858416])

In [28]:
np.random.randint(0,100,10)

array([19, 39, 56,  0, 93, 11, 80,  3, 42, 35])

In [30]:
arr = np.random.rand(25)

In [31]:
arr

array([0.9969957 , 0.25798096, 0.33937914, 0.68202096, 0.02763508,
       0.3742637 , 0.22673222, 0.90762384, 0.33888579, 0.30651272,
       0.26184094, 0.17294814, 0.85709249, 0.41445837, 0.12602887,
       0.16648386, 0.5765857 , 0.87690591, 0.55520178, 0.53680665,
       0.3324072 , 0.16997881, 0.93437711, 0.34927743, 0.5851251 ])

In [32]:
arr.reshape(5,5)

array([[0.9969957 , 0.25798096, 0.33937914, 0.68202096, 0.02763508],
       [0.3742637 , 0.22673222, 0.90762384, 0.33888579, 0.30651272],
       [0.26184094, 0.17294814, 0.85709249, 0.41445837, 0.12602887],
       [0.16648386, 0.5765857 , 0.87690591, 0.55520178, 0.53680665],
       [0.3324072 , 0.16997881, 0.93437711, 0.34927743, 0.5851251 ]])

In [33]:
arr

array([0.9969957 , 0.25798096, 0.33937914, 0.68202096, 0.02763508,
       0.3742637 , 0.22673222, 0.90762384, 0.33888579, 0.30651272,
       0.26184094, 0.17294814, 0.85709249, 0.41445837, 0.12602887,
       0.16648386, 0.5765857 , 0.87690591, 0.55520178, 0.53680665,
       0.3324072 , 0.16997881, 0.93437711, 0.34927743, 0.5851251 ])

In [34]:
arr = arr.reshape(5,5)

In [35]:
arr

array([[0.9969957 , 0.25798096, 0.33937914, 0.68202096, 0.02763508],
       [0.3742637 , 0.22673222, 0.90762384, 0.33888579, 0.30651272],
       [0.26184094, 0.17294814, 0.85709249, 0.41445837, 0.12602887],
       [0.16648386, 0.5765857 , 0.87690591, 0.55520178, 0.53680665],
       [0.3324072 , 0.16997881, 0.93437711, 0.34927743, 0.5851251 ]])

In [36]:
arr.shape

(5, 5)

In [37]:
arr.max()

0.9969957047709768

In [38]:
arr.min()

0.027635084681901678

In [39]:
arr.argmax()

0

In [40]:
arr.argmin()

4